# 智付通測試平台: https://cwww.spgateway.com/
# 信用卡測試卡號: 4000-2211-2222-2222

default: &default
  merchant_id: MS36020511
  hash_key: CpQYshVvq9eqcUNNoR1lJlkfib8RqiOu
  hash_iv: IXTW5Pyygkpl52s8
  url: https://ccore.spgateway.com/MPG/mpg_gateway
  notify_url: http://requestbin.fullcontact.com/1e6ars71

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default